import React, { useEffect } from 'react';
import { Link } from 'react-router-dom';
import { ArrowLeft, Scale, AlertTriangle, ShieldAlert, Coins, Bot, Gavel, FileWarning, Copyright, HelpCircle, UserX } from 'lucide-react';

export const TermsAndConditions = () => {
  useEffect(() => {
    window.scrollTo(0, 0);
  }, []);

  return (
    <div className="min-h-screen bg-slate-900 text-slate-300 font-rajdhani relative overflow-hidden selection:bg-red-500 selection:text-white pb-20">
      {/* Background Effects */}
      <div className="fixed inset-0 pointer-events-none opacity-[0.4]" 
           style={{ backgroundImage: 'linear-gradient(rgba(239,68,68,0.1) 1px, transparent 1px), linear-gradient(90deg, rgba(239,68,68,0.1) 1px, transparent 1px)', backgroundSize: '40px 40px' }}>
      </div>
      <div className="fixed inset-0 pointer-events-none bg-[radial-gradient(circle_at_center,transparent_0%,#0f172a_100%)]"></div>

      <div className="container mx-auto max-w-4xl px-6 pt-12 relative z-10">
        <Link to="/" className="inline-flex items-center gap-2 text-red-500 hover:text-white transition-colors font-mono text-sm uppercase tracking-widest mb-12 group">
          <ArrowLeft className="w-4 h-4 group-hover:-translate-x-1 transition-transform" />
          Return to System
        </Link>

        <div className="mb-16 text-center md:text-left">
          <div className="inline-flex items-center justify-center w-16 h-16 rounded-2xl bg-red-500/10 border border-red-500/30 mb-6 shadow-[0_0_30px_rgba(239,68,68,0.2)]">
            <Scale className="w-8 h-8 text-red-500" />
          </div>
          <h1 className="text-4xl md:text-6xl font-bold text-white mb-4 font-serif tracking-wider uppercase drop-shadow-[0_0_10px_rgba(239,68,68,0.3)]">
            Terms & <span className="text-red-500">Conditions</span>
          </h1>
          <div className="text-red-500 font-mono text-sm tracking-[0.3em] uppercase animate-pulse">
            Last Updated: April 2026 // Legal Framework Active
          </div>
        </div>

        <div className="space-y-12 bg-slate-800/40 backdrop-blur-md border border-slate-700/50 p-8 md:p-12 rounded-3xl shadow-2xl">
          
          <section className="space-y-4">
            <h2 className="text-2xl font-bold text-white flex items-center gap-3 border-b border-slate-700 pb-4">
              <FileWarning className="w-6 h-6 text-red-500" />
              1. Acceptance of Terms
            </h2>
            <div className="space-y-4 text-lg leading-relaxed">
              <p>
                By downloading, installing, accessing, or utilizing the REFORGE application in any capacity, you are entering into a legally binding agreement and explicitly consenting to these Terms and Conditions. These foundational rules are established to ensure that the game remains fair, safe, competitive, and enjoyable for all participating Hunters globally.
              </p>
              <p className="text-red-400 font-bold uppercase tracking-wider text-sm">
                If you disagree with any of these rules, stipulations, or penalties, you are instructed to immediately uninstall the application and cease all usage.
              </p>
            </div>
          </section>

          <section className="space-y-4">
            <h2 className="text-2xl font-bold text-white flex items-center gap-3 border-b border-slate-700 pb-4">
              <AlertTriangle className="w-6 h-6 text-red-500" />
              2. NOT MEDICAL ADVICE (Critical Warning)
            </h2>
            <div className="bg-red-950/30 border border-red-500/30 p-6 rounded-xl space-y-4 text-lg">
              <p className="font-bold text-white uppercase">REFORGE is strictly a gamified motivational tool. It is NOT a doctor, a physical therapist, or a licensed medical professional.</p>
              <p>
                The workout regimens, caloric expenditure recommendations, and all physiological advice dispensed by the DUSK AI are generated by complex algorithms. They are mathematical estimates, not clinical diagnoses. By utilizing this application, you legally acknowledge and agree that:
              </p>
              <ul className="list-disc pl-6 space-y-3 text-slate-300 marker:text-red-500">
                <li>You are physically healthy, capable, and medically cleared to engage in strenuous exercise.</li>
                <li>You will consult a certified, real-world physician before commencing any new dietary protocol or intense fitness program suggested by the System.</li>
                <li><strong className="text-white">If you experience pain, dizziness, nausea, or illness while executing a quest, you will STOP IMMEDIATELY.</strong></li>
                <li><strong className="text-red-400">You will not sue us.</strong> The creators, developers, and corporate entities behind REFORGE are entirely absolved of responsibility for any physical injuries, health complications, psychological distress, or damages you might suffer while attempting to complete quests within the application. You exercise entirely at your own risk.</li>
              </ul>
            </div>
          </section>

          <section className="space-y-4">
            <h2 className="text-2xl font-bold text-white flex items-center gap-3 border-b border-slate-700 pb-4">
              <ShieldAlert className="w-6 h-6 text-red-500" />
              3. The Rules of the Game (Anti-Cheat Protocol)
            </h2>
            <p className="text-lg mb-4">This application relies fundamentally on your personal integrity and honesty. To maintain the absolute integrity of the global leaderboards, you are strictly forbidden from cheating. Cheating includes, but is in no way limited to:</p>
            
            <div className="grid sm:grid-cols-2 gap-4 mb-6">
              <div className="bg-slate-900/50 p-4 rounded-lg border border-slate-700">
                <p className="text-sm">Lying about or misrepresenting the completion of a physical workout.</p>
              </div>
              <div className="bg-slate-900/50 p-4 rounded-lg border border-slate-700">
                <p className="text-sm">Uploading fabricated photos, images sourced from the internet, or photographs of a digital screen.</p>
              </div>
              <div className="bg-slate-900/50 p-4 rounded-lg border border-slate-700">
                <p className="text-sm">Employing GPS spoofing applications or emulators to artificially inflate your running or walking distance.</p>
              </div>
              <div className="bg-slate-900/50 p-4 rounded-lg border border-slate-700">
                <p className="text-sm">Manipulating device sensors (e.g., shaking your phone while sedentary) to artificially generate walking steps.</p>
              </div>
            </div>

            <div className="bg-slate-800/50 p-6 rounded-xl border-l-4 border-red-500">
              <h3 className="text-xl font-bold text-white mb-2">The ForgeGuard System</h3>
              <p className="text-lg">
                We deploy advanced AI heuristics to actively detect and neutralize cheaters. If our system detects anomalous behavior—such as traveling at 60km/h during a designated "walking" quest, or submitting cryptographically invalid images—you will be issued a formal <strong className="text-red-500">"Cheat Strike."</strong>
              </p>
              <p className="text-lg mt-2 font-bold text-white">
                Accumulating 3 Cheat Strikes will result in your account being permanently banned from the global leaderboards, and your Hunter level will be irreversibly reset to zero.
              </p>
            </div>
          </section>

          <section className="space-y-4">
            <h2 className="text-2xl font-bold text-white flex items-center gap-3 border-b border-slate-700 pb-4">
              <Coins className="w-6 h-6 text-red-500" />
              4. Virtual Currency (Gold and Keys)
            </h2>
            <p className="text-lg leading-relaxed">
              As you progress through the System, you will earn virtual assets designated as "Gold" and "Keys." You possess the ability to pledge Gold to "System Pacts" as a psychological motivational tool. Should you fail to uphold a pact, your pledged Gold is "burned" (permanently destroyed).
            </p>
            <p className="text-lg leading-relaxed font-bold text-white bg-slate-900/50 p-4 rounded-lg border border-slate-700">
              Please understand unequivocally: Gold and Keys are completely fabricated digital points. They possess absolute zero real-world monetary value. You cannot cash them out, transfer them to a financial institution, or sell them to other players. "Burning" gold is exclusively an in-game punitive mechanic designed to induce psychological friction so you exert more effort in subsequent quests. It does not cost you actual fiat currency.
            </p>
          </section>

          <section className="space-y-4">
            <h2 className="text-2xl font-bold text-white flex items-center gap-3 border-b border-slate-700 pb-4">
              <Bot className="w-6 h-6 text-red-500" />
              5. The DUSK AI Coach
            </h2>
            <p className="text-lg leading-relaxed">
              DUSK is an advanced Artificial Intelligence entity engineered to function as a strict, uncompromising, and occasionally arrogant accountability partner. DUSK is programmed to utilize harsh, direct language (e.g., "You are weak," "Get off the couch") to aggressively motivate you.
            </p>
            <p className="text-lg leading-relaxed">
              By utilizing the application, you explicitly consent to this aggressive style of communication. If you find DUSK's personality offensive, distressing, or detrimental to your mental well-being, you are instructed to immediately cease using the application. Remember at all times that DUSK is merely executing code and is entirely incapable of providing actual psychological, psychiatric, or medical advice.
            </p>
          </section>

          <section className="space-y-4">
            <h2 className="text-2xl font-bold text-white flex items-center gap-3 border-b border-slate-700 pb-4">
              <Gavel className="w-6 h-6 text-red-500" />
              6. The Penalty Zone
            </h2>
            <p className="text-lg leading-relaxed">
              Should you fail to authenticate daily or neglect to complete your mandatory requirements, the System will automatically relegate your account to the "Penalty Zone." This state actively locks specific features and functionalities of the application until you complete a designated physical punishment (such as executing 100 pushups or running 5km). This is a foundational, non-negotiable core game mechanic. You cannot bypass the Penalty Zone by submitting complaints to customer support. <strong className="text-white">You must do the work.</strong>
            </p>
          </section>

          <section className="space-y-4">
            <h2 className="text-2xl font-bold text-white flex items-center gap-3 border-b border-slate-700 pb-4">
              <UserX className="w-6 h-6 text-red-500" />
              7. Account Rules
            </h2>
            <p className="text-lg leading-relaxed">
              You are strictly limited to maintaining one (1) single account per individual human. You are expressly forbidden from sharing your account credentials with associates to artificially accelerate your ascent on the leaderboard. We reserve the absolute, unchallengeable right to suspend, ban, or permanently delete any account at any time, for any reason, without prior warning—especially in instances where we detect cheating or attempts to compromise the application's security infrastructure.
            </p>
          </section>

          <section className="space-y-4">
            <h2 className="text-2xl font-bold text-white flex items-center gap-3 border-b border-slate-700 pb-4">
              <Copyright className="w-6 h-6 text-red-500" />
              8. Intellectual Property
            </h2>
            <p className="text-lg leading-relaxed">
              Every element contained within this application—including the underlying source code, the UI/UX design, the visual artwork, the textual content, and the proprietary DUSK AI personality matrix—is the exclusive intellectual property of REFORGE. You are strictly prohibited from copying, stealing, reverse-engineering, or utilizing our proprietary assets to develop your own application or derivative works.
            </p>
          </section>

          <section className="space-y-4">
            <h2 className="text-2xl font-bold text-white flex items-center gap-3 border-b border-slate-700 pb-4">
              <FileWarning className="w-6 h-6 text-red-500" />
              9. Changes to the Terms
            </h2>
            <p className="text-lg leading-relaxed">
              The System is in a state of constant evolution and refinement. We reserve the right to modify, amend, or overhaul these terms at any point in the future. We will issue a notification when such modifications occur. Continuing to engage with the game following these updates constitutes your irrevocable acceptance of the new ruleset.
            </p>
          </section>

          <section className="space-y-4">
            <h2 className="text-2xl font-bold text-white flex items-center gap-3 border-b border-slate-700 pb-4">
              <HelpCircle className="w-6 h-6 text-red-500" />
              10. Contact Us
            </h2>
            <p className="text-lg leading-relaxed">
              If you require clarification regarding these terms, or if you wish to formally appeal a ban because you believe the ForgeGuard Anti-Cheat system generated a false positive, please direct your communications to our support matrix at: <a href="mailto:reforgesystem@gmail.com" className="text-red-500 hover:text-white transition-colors underline">reforgesystem@gmail.com</a>.
            </p>
            <p className="text-lg leading-relaxed">
              <strong className="text-white">Registered Operations:</strong> Maharashtra, India.
            </p>
          </section>

        </div>
      </div>
    </div>
  );
};
